### PR TITLE
fixed odataGenColModel and made it more intelligent

### PR DESCRIPTION
**Pull request by mirik123**

### CODE REVIEW

**Comment by mirik123** [comment]
changed also functions order

**Comment by OlegKi** [comment]
The plugin looks good! I'll merge it immediately. [The example](https://github.com/mirik123/jqGridSamples) needed be changed sure more (I mean not only `$.jgrid.errors.errcap` and `$.jgrid.edit.bClose` which are undefined now), but it's in separate project and one can't do all things at once. Thank you!

**Comment by mirik123** [comment]
updated sample projects

**Comment by OlegKi** [comment]
OK! I see, but you use `$this` variable which is undefined. You need to add `var $this = $(this);` inside of  `loadError` callback. Additionally I would find interesting to replace `colModelDefinition` to call of `odataGenColModel`. I don't see any call of `odataInit` too. I find that the plugin will be really good if you (and other) could use it easy. If you see some problems which you can write me about there. Probably some changes in the main jqGrid code would makes such scenarios more easy to implement.

**Comment by mirik123** [comment]
Hi,
I updated jqGridSamples.
odataInit function is called inside beforeInitGrid because it is the only place where colModel can be set and it is relevant only for OData.
The WebApi configuration uses server-side directly without fitting client-side first.
If you have tasks for improving the odata plugin you can open me issues.
I'm now thinking how to set colModel asynchronously.

**Comment by OlegKi** [comment]
Thank you! The question about asynchronous initialization of `colModel` is absolutely correct. It's what I want to implement soon.
I'll examine your example carefully later. The first remark: I'd recommend you to change the line
```csharp
config.Formatters.JsonFormatter.SerializerSettings.PreserveReferencesHandling =
    PreserveReferencesHandling.None;
```
from `WebApiConfig.cs` to 
```csharp
config.Formatters.JsonFormatter.SerializerSettings.PreserveReferencesHandling =
    PreserveReferencesHandling.Objects;
```
(or to `PreserveReferencesHandling.All`). It will allow to use `http://localhost:56216/odata/$metadata` with `Accept: application/json`. In other words one could get Metadata in JSON format.

**Comment by mirik123** [comment]
updated sample project.

**Comment by OlegKi** [comment]
Look at [the demo](www.ok-soft-gmbh.com/jqGrid/OK/OData/Demo.zip) project which I created based on [the example](http://www.odata.org/blog/how-to-use-web-api-odata-to-build-an-odata-v4-service-without-entity-framework/) and which uses your plugin. It seems me small and good to understand. It's far to be final, but I think it could be interesting for you.
I will make soon some changes in jqGrid code to allow to make asynchronous generation of `colModel`.

**Pull request merged**
