### PR TITLE
Update grid.odata.js

### PR DESCRIPTION
**Pull request by mirik123**
Fixed numerous bugs and added support for standard odata services from http://www.odata.org/odata-services

### CODE REVIEW

**Comment by OlegKi** [comment]
It looks good. I'll merge it.

I recommend you only to verify the code always in [JSLint](http://old.jslint.com/) or JSHint. One will see that one can remove unused `partner` variables and to replace `==` to `===` in `if (m == "{{") { return "{"; }` and in `if (m == "}}") { return "}"; }`. The improvements are not really important, but there are correct.

Best wishes!

**Comment by OlegKi** [comment]
What do you think about writing new [wiki](https://github.com/free-jqgrid/jqGrid/wiki) article where you provides some information about your jqGrid OData plugin? I personally find it very interesting, but I'm afraid that not so many users of jqGrid/free jqGrid know it.

**Comment by mirik123** [comment]
Hi,
Thanks for accepting pull request.
Yes, I think it will be a good idea to write a wiki article.
I also see that the free-jqgrid versions in NuGet and NPM are quite obsolete.
Is there a chance to update them to the latest versions?

**Comment by OlegKi** [comment]
I will publish free jqGrid 4.9-beta1 in the next days. It will be accessibly over all the sources. I will publish the release 4.9 about two weeks later.

**Pull request merged**
