### PR TITLE
Updated _registerAddEvents

### PR DESCRIPTION
**Pull request by Luca7993**
I have added the code for moving the option element to the end.
Without this, when I "show" a column, it is placed at the original position in the grid

### CODE REVIEW

**Comment by OlegKi** [comment]
Sorry, but you should describe the problem more exactly. It would be good to prepare the demo and the test case, which reproduces the problem. It should be absolutely clear that we have a bug. The plugin uses `jQuery.data` method to set explicitly `idx` and `optionLink` and it restores the original position of the column in some scenarios. For example, by clicking on "Remove all" button and then "Add all" one will have the items in the same order as it was originally.

I want exactly understand the problem, which you try to fix, to be sure that the changes really improve the code and that they doesn't have any side effects.

Moreover the file `ui.multiselect.js` are included in `plugin` directory in the **original** form. The module of jqGrid `grid.jqueryui.js` uses `"ui.multiselect"` in the `columnChooser` method. [The lines](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.jqueryui.js#L48-L60) changes the **original** method `_setSelected` to a little modified implementation. The new method calls the original `_setSelected` first and then some additional actions will be executed. The actions are close to the changes, which you suggest.

**Comment by Luca7993** [comment]
Hi Oleg,
I have prepared the demo that explain the problems (and also another problem with hide and show).
[Original Column Chooser](http://testjqgridalimede.azurewebsites.net/Home/ColumnChooser?type=original)
[Problem with show and hide solved](http://testjqgridalimede.azurewebsites.net/Home/ColumnChooser?type=edit1)
[My Solution](http://testjqgridalimede.azurewebsites.net/Home/ColumnChooser?type=edit2)

thank you

**Comment by OlegKi** [comment]
Thank you very much for the demos. The test case with clicking on Remove all and then Add all was the most important for me to see that the code of `ui.multiselect.js` is buggy. I made some modifications. Please try https://rawgit.com/free-jqgrid/jqGrid/master/plugins/ui.multiselect.js and verify whether the same problem is still exist. If it's exist, please describe the test case, which can be used to reproduce the problem, step by step.

**Comment by Luca7993** [comment]
Hi Oleg,
your changes has solved the first problem.
it remains the problem about positioning, I indicate also the steps for reproduce problems
[Original Column Chooser](http://testjqgridalimede.azurewebsites.net/Home/ColumnChooser?type=original)
[I solved it in this way](http://testjqgridalimede.azurewebsites.net/Home/ColumnChooser?type=edit)

thank you
Luca

**Comment by OlegKi** [comment]
Sorry for the late answer. You are right with the poll request, but the origin of the problem should be fixed [here](https://github.com/free-jqgrid/jqGrid/commit/53184572c49ba009016738339a1b5be7f18b1d8b). The problem is old and the fix is already exist in `grid.jqueryui.js` (instead of modifying the original `ui.multiselect.js`). The problem was that `this` was changed to wrong `self` value during some other changes of the code. I fixed the code now.

Thank you for reporting of the problem!

**Comment by Luca7993** [comment]
Hi Oleg,
thank you for solving the problem!

**Pull request closed without merging**
