### PR TITLE
Include missing documentation

### PR DESCRIPTION
**Pull request by askrinnik**
Hi Oleg,
I used JqGrid on JavaScript. Then I rewrote code to TypeScript. It was found that some options are not declared or declared not quite correct in te TypeDefenition file. 
I made some changes in d.ts file
Could you, please, take a look to my changes?

### CODE REVIEW

**Comment by OlegKi** [comment]
Thank you very much for the changes! Everything seems be correct, with exception of  `value` property of `EditOptions`. It seems to me that one can't use it as function. I'll remove the part `() => string` after merging your pull request.

**Comment by askrinnik** [comment]
Oleg, 
as I see here https://github.com/free-jqgrid/jqGrid/blob/master/js/jquery.jqgrid.src.js#L2520
value can be a function.  We use this feature in our project

**Comment by OlegKi** [comment]
I posted [the commit](https://github.com/free-jqgrid/jqGrid/commit/6c96419a149063492faa47c0a4c74ea915ee06e3) just now. I described the problem and the solution more detailed in the comment to the commit. I think that the latest definition of `EditOptions` is good enough and you will have no problem with compiling of your code with the latest version of `free-jqgrid.d.ts`.

It's pity, but I don't now how one can specify in TypeScript, that `editoptions.value` as function is allowed only in combination with `editable: "select"`. Nobody is perfect.

**Comment by askrinnik** [comment]
OK.
I'm waiting a new version of nUget package and then I'll refactor my code
Thanks!

**Pull request merged**
