### PR TITLE
fixed bugs in grid.odata.js

### PR DESCRIPTION
**Pull request by mirik123**
TODO:
1) add support for {gencolumns:true, async:true}.
2) add support for jsonp GET requests.
4) add function to reinit grid after colModel change.
3) fix bug: "Uncaught TypeError: Cannot read property 'iconSet' of undefined" at grid.common.js:120

### CODE REVIEW

**Comment by OlegKi** [comment]
OK, Mark I will merge the pull request.
Just some small additional suggestion to you:
* the code will be easier to validate if you would change the order of functions inside of `odataInit`. It's clear that one can define function statement on the any place, but Douglas Crockford recommend first to define the function and then use it. Probably it can improve performance of parsing JavaScript code. In any way I personally follow the rule. So you can just use the code of `odataInit` like below:
```JavaScript
odataInit: function (options) {
    function prepareExpression(p, searchField, searchString, searchOper) {
        ...
    }
    function parseFilterGroup(filterGroup, p) {
        ...
    }
    function setupWebServiceData(p, o, postData) {
        ...
    }
    function initDefaults(p, o) {
        ...
    }
    return this.each(function () {
        ...
    });
}
```
Another remark. Are you sure that
```JavaScript
 filterText = filterText.trim().replace(/.(and|or)$/, '').trim();
```
uses the RegEx which you really need? Is  `/(and|or)$/` or `/\w(and|or)$/` would be better as `/.(and|or)$/`?

One more line of code I'v seen:
````JavaScript
if (o.datatype === 'jsonp') { o.callback = "jsonCallback_" + Math.floor((Math.random() * 1000) + 1); }
````
Probably you want to generate **unique** callback name. I spend some time two years ago because I wanted to suggest some good method to generate unique ids for some jqGrid elements. The method `Math.random` is not safe, and and tricks with `new Date` which one can frequently see are also not safe. The solution was to use simplest `$.jgrid.randId()`. It is very simple and really safe. jQuery and jQuery UI uses the same approach. So I would suggest you to use something like
````JavaScript
if (o.datatype === 'jsonp') { o.callback = "jsonCallback_" + $.jgrid.randId(); }
````

**Comment by mirik123** [comment]
Oleg hi,
Thanks for your remarks.
I added sample projects that show intercation of jqGrid qith OData and WebApi:
https://github.com/mirik123/jqGridSamples
The detailed readme file will be added soon.

**Comment by OlegKi** [comment]
Thank you for the post. I looked through the demos. I have the following suggestions:

1. You should update `ui.jqgrid.css` used in projects. It's old one.
2. I recommend you to include `jquery.jqGrid.src.js` or `jquery.jqGrid.min.js`, instead of a lost of separate modules, and to include `plugins` directory with your `grid.odata.js` plugin.
3. You should use `grid.odata.js` plugin which you posted. The mostly interesting part of your plugin generates `colModel` from metadata of the OData service. The demos don't use it.
4. You should hold naming conversion of JavaScript language in the code. If you start the name of the function with capital letter, it means in JavaScript that the function is **constructor** of an object and one should use `new` operator to create the instance of the object. So the names of functions `InitODataTable`, `InitWebApiTable`, `LinkFormatter`, `LinkUnformatter` and many other **are wrong**. JavaScript only looks close to the syntax of C# or Java, but it has absolutely another semantic in many cases. It's strictly recommended to hold the naming conversion. If you know the name of JavaScript function like `Date`, then you know the correct usage of it: `var myDate = new Date();` and not `var myDate = Date();`. All well-known text editors, and text formatters (like prettify used on stackoverflow)  know the naming conversion and displays the names with the first capital letter in *another color*. So it's really important to hold correct naming conversion (correct for the language used).
5. You should **never** define unneeded *global* variables and global functions in your JavaScript code. The current code of `InitTables.js` defines many *global* variables, which will be assigned as properties of `window` object. It's very bad practice. Instead of using

**Default.html**:
```html
<script type="text/javascript">
    $(document).ready(function () {
        InitODataTable();
    });
</script>
```

and
**InitTables.js**:
```JavaScript
function InitWebApiTable() {
    ...
}
function InitODataTable() {
    ....
}
...
function LinkUnformatter(cellvalue, options, cell) {
    ...
}
```

You can just use
**Default.html**:
```html
<script src="/Scripts/custom/InitTables.js"></script>
```

where `$(document).ready` are moved *inside of** `InitTables.js`:
**InitTables.js**:
```JavaScript
$(document).ready(function() {
    function linkUnformatter(cellvalue, options, cell) {
        ...
    }
    ...
    function initODataTable() {
        ...
    }
    initODataTable();
});
```

As I mention early, it's recommended to define the function before it will be used. So the changing of the order of the functions is recommended too.

One more small advice. You use permanently wrong compare operations `==` and `!=` in your code. It doesn't matter that you used to use the operations in C#. JavaScript have *another operations and it's own semantic* (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness)) for example. The compare `cellvalue.href == null` means **the same as** `cellvalue.href === null || cellvalue.href === undefined` and the compare `cellvalue.href == ''` needed be **always** rewritten as `cellvalue.href === ''` because both operands should be interpreted as strings. Additionally one should **always** use `{}` after `if` or `else`. JavaScript can insert unneeded semicolon in difference to C#, so what is permitted for C# can be evil for JavaScript. All parameters of callback functions are *optional* so one should skip declaration of unused variables (see for example the last `rowObject` option of `LinkFormatter`). The code of `LinkFormatter` is the good example of correct C# code and very bad JavaScript code. Sorry.

If you use active C# language, that you know probably [ReSharper](https://www.jetbrains.com/resharper/). It's very good tool, which I subscribed since years. The tool have support of JavaScript too and it will gives you the same recommendations as I described above. It will help you to improve a little your C# code too, but the changes are not so important as the changes in JavaScript code.

**Comment by mirik123** [comment]
Oleg, hi.
I updated the sample solution according to jacascript best practices as you proposed.
I also added a fix to odata plugin to generate colModel more intelligent.
When I finish fighting with GIT I create a pull request.

**Comment by OlegKi** [comment]
Hi Mark,

I posted recently free jqGrid 4.8.0 which includes our last version of `grid.odata.js` to [nuget](https://www.nuget.org/packages/free-jqGrid), CDN. Your plugin for example can be loaded from  `//cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.8.0/plugins/grid.odata.js` (with optional `http:` or `https:` prefix).

I forgot the write you additionally that the code of `loadError` where you use `$.jgrid.errors.errcap` and `$.jgrid.edit.bClose` directly needed be fixed to use `getGridRes` method:
```JavaScript
loadError: function (jqXHR, textStatus, errorThrown) {
    var $this = $(this), errstring = loadError(jqXHR, textStatus, errorThrown);
    $.jgrid.info_dialog.call(this,
        $this.jqGrid("getGridRes", "errors.errcap"),
        errstring,
        $this.jqGrid("getGridRes", "edit.bClose")
    );
}
```

**Pull request merged**
