### PR TITLE
added support to WebApi odata v4 

### PR DESCRIPTION
**Pull request by mirik123**
P.S. the commit "Merge remote-tracking branch 'upstream/master'" has been added automatically.
I beleave it contains the merges form your branch so, you don't need to pull it back?

### CODE REVIEW

**Comment by mirik123** [comment]
The server-side code that generates odata annotations necessary to communicate with jqGrid has been added to https://github.com/mirik123/jqGridWebApi.

**Comment by OlegKi** [comment]
I can't merge the pull request because of many criteria:
1. I can't verify [the Merge remote-tracking branch 'upstream/master'](https://github.com/mirik123/jqGrid/commit/19df70c279ef6aba92322c4c4ed4f157fd2ab871) part. I suspect additionally that merging of such part will follow conflicts with existing changes which I did before.
2. It seems that you try to change the signature of `getAccessor` method (see [the part](https://github.com/mirik123/jqGrid/commit/1b1205d91385f8d9a913822c42deaab657842bc3) of the pull request). I see no reason of such changes. One can use function inside of `jsonReader`. I see **no requirement** for such changes. So I have to reject there.

I looked through the code of `grid.odata.js`. It's really dirty. I strictly recommend you to update it.

First of all the code use such constants like `http://localhost:59661`,  ` "#grid"`, `'#gridpager'` and so on. So **the code is not plugin** to jqGrid. It's just a part of some example (JavaScript code without the corresponding HTML code or C# code of the server code). 

Seconds the JavaScript code from `grid.odata.js` is dirty. There are no `(function ($) {...}}(jQuery));` over the code. So **all the code global context**. You defines *global* functions `InitJqGridODataSample`, `GetODataMetadata` (which are properties of `window` object), you set `"use strict"` on the global level and can break some other JavaScript code which can be included on the same page. You use `$` on the top level instead of defining `$` as *local* variable based on global variable `jQuery` (one follow the rule in all plugins). You use `==` instead of `===` if you compare strings or compare with `undefined` (see `options.extraparam.oper == 'edit'`, `frmoper == 'add'`, `frmoper == 'edit'`, `data["odata.nextLink"] != undefined`), you skip radix parameter (the second  parameter) of `parseInt`, which should be 10 in everywhere in your code. You should *always* include {} after `if` in the code (see [the lines](https://github.com/mirik123/jqGrid/blob/master/plugins/grid.odata.js#L282-L283) or [the lines](https://github.com/mirik123/jqGrid/blob/master/plugins/grid.odata.js#L262-L269) and many other places). Such style is evil for JavaScript (but it's absolutely correct in other languages). I can continue...

What you shell do is rewriting of the code so that it defines for example new method jqGrid (like [here](https://github.com/OlegKi/jqGrid-plugins/blob/master/jQuery.jqGrid.setColWidth.js)). In the way you could provide some reusable code which other can use directly. The current code of `grid.odata.js` is really mot much more as code fragment. Sorry.

**Comment by mirik123** [comment]
Hi,
Thanks for constructive and deep explanations.
1) this commit is added by mistake, it should not be merged.

2) the getAccessor's signature is not changed and is backward-compatible. Right now the expr parameter can be one of "object" or "function" types, I introduced also to allow it to be an "Array" type. It is true that the added functionality can be reached by defining function but, by my opinion, the new code adds readability as shown in example.
before:
jsonReader: {records: function (data) {return data['@jqgrid.GridModelAnnotate'].records;}}
after:
jsonReader: {records: ['@jqgrid.GridModelAnnotate', 'records']}

3.1) the plugin file contains both the odata code as well as an example of how to use it.
If there is a misunderstanding I can move example code to separate file.
3.2) the plugin can included to original jqGrid code in 3 ways: 
overwriting the original jqgrid files, 
setting the $.jgrid.inlineEdit/$.jgrid.edit/$.jgrid.defaults,
setting the events like jqGridInlineBeforeSaveRow, jqGridInlineClickSubmit
which way is correct?

**Comment by OlegKi** [comment]
Hi Mark,

to point 2. What I man is that I see **no need (no real requirement)** to change the signature of the `getAccessor` (the number and the type of parameters is the part of signature). If one can implement existing requirements using existing signature of `getAccessor` and existing possibility of `jsonReader` then I will not change the existing implementation. Before one start to change something one should ask the question: Why? The answer on the question is more close to "just for fun" as "I can't implement my requirement without the changes". So you should just use *existing* possibilities of `jsonReader` and `getAccessor` in your plugin.

To 3 1). I recommend you to take a look in [jqPivot](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:pivotsettings) method. The method have input `data` and some other options. It scan the data based on the options, generates `colModel` and the it creates the grid. Even the old and dirty written method [tableToGrid](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:table_to_jqgrid) do close things. If you want to generate `colModel` based on some metadata returned from some URL that you can follow the same way and create new method with the required number of parameters.  the URLs like `"http://localhost:59661/odata/ODClient"` could be inside of options of your method. By the way you should never use dirty option `async: false` of jQuery.ajax. It would be good if you allows to use JSON and not only XML as the output from `$metadata` which is allowed too (see [here](https://msdn.microsoft.com/en-us/library/ff478141.aspx)). One need just use `$format=json` or better `$format=application/json` (which corresponds [OData specification](http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata02/os/odata-json-format-v4.0-errata02-os-complete.html#_Toc403940603)).

What I mean: one don't need any code example in plugin directory. One need to have new jqGrid method which helps to access (which simplify the access) of OData services.

To 3.2). If you change the values of `$.jgrid.inlineEdit/$.jgrid.edit/$.jgrid.defaults` then you a) change the values of **all grids on the page** (not all grids have to access OData service) b) You overwrite some other settings which the user use ad defaults like `rowNum: 25` which will be used for *all* grids and subgrids on the page. It's very bad.

Look at the code of [the old plugin](https://github.com/OlegKi/jqGrid-plugins/blob/master/jQuery.jqGrid.fontAwesome4.js) which I wrote for usage with jqGrid 4.6/4.7. It changes default property only if there are no other way (which do exist in my new version of jqGrid). In [the part of code](https://github.com/OlegKi/jqGrid-plugins/blob/master/jQuery.jqGrid.fontAwesome4.js#L151-L256) it register `jqGridFilterAfterShow`, `jqGridAddEditBeforeShowForm` and other events. So the plugin do some work at therequired moment, but it don't overwrite callbacks like `beforeShowForm` or `beforeShowSearch`. So the user can continue to use his existing code and just add `.jqGrid("initFontAwesome")` call. See [the answer](http://stackoverflow.com/a/20165553/315935). So by usage of `$("#grid").jqGrid("initFontAwesome").jqGrid({...});` instead of `$("#grid").jqGrid({...});` one get new functionality.

I introduced in my fork of jqGrid new callback `beforeInitGrid` and the event `jqGridBeforeInitGrid`. the callback can be used like `onInitGrid` and `jqGridInitGrid` to make changes in existing options of jqGrid, but `beforeInitGrid` and `jqGridBeforeInitGrid` will be called **before all**. So it's possible for example to  allow to use `colModel: "OData"` or ``colModel: "OData:http://localhost:59661/odata/ODClient"``. Inside of `beforeInitGrid` and `jqGridBeforeInitGrid` one can modify `colModel` to another value and jqGrid will process already modified data. The only problem in the scenario: you can't make asynchronous processing in the way. So the way like `jqPivot`/`tableToGrid` do have more advantades in the asynchronous scenario.

My fork of jqGrid allows to set all editing parameters using `inlineEditing`, `searching`,  `formEditing`, `formViewing` and `formDeleting` options. It's better to use the options instead of `$.jgrid.inlineEdit`, `$.jgrid.edit` and `$.jgrid.del` because one set in the way the option **for the current grid only** instead of changing default options for all grids on the page. Just try to use `formDeleting: {mtype: "DELETE", ajaxDelOptions: {contentType: "application/json;charset=utf-8"}}` instead of ` $.extend(true, $.jgrid.del,  {mtype: "DELETE", ajaxDelOptions: {contentType: "application/json;charset=utf-8"});`.

**Comment by OlegKi** [comment]
Hi Mark,

I see that you made many changes in `grid.odata.js`. The current code is still for from the final solution. First of all you should fix many syntax errors. The current code
````JavaScript
(function($){
"use strict";
$.jgrid.extend({
	setColModelMetadata: function (savecolfunc, successfunc, errorfunc) {
            ...
	}
	initODataDefaults: function (p) {
            ...
	}
	setupWebServiceData: function (postData) {
            ...
	}
	odataExpression: function (op, field, data) {
            ...
	}
	parseFilterGroup: function (filterGroup) {
            ...
	}
}(jQuery));
````
need be fixed to
````JavaScript
(function($){
"use strict";
$.jgrid.extend({
	setColModelMetadata: function (savecolfunc, successfunc, errorfunc) {
            ...
	},
	initODataDefaults: function (p) {
            ...
	},
	setupWebServiceData: function (postData) {
            ...
	},
	odataExpression: function (op, field, data) {
            ...
	},
	parseFilterGroup: function (filterGroup) {
            ...
	}
});
}(jQuery));
````
The current code have many other syntax errors, like usage of undefined `$t`, `p`, `$self` and other variables in many places of the code. You should define functions as new jqGrid method only if it have meaning for other users. The function `parseFilterGroup` for example seems to have some meaning only inside of `setupWebServiceData`. So it can be defined inside of the method and not be declared on the top level.

One more important remark. If you define new jqGrid method like `setColModelMetadata` then `this` inside of the method will be jQuery wrapper of DOM of `<table>` and not the DOM itself. So you should use either 
````JavaScript
$.jgrid.extend({
	setColModelMetadata: function (savecolfunc, successfunc, errorfunc) {
		return this.each(function(){
			var $t = this;
			...
		});
	}
});
````
if you wnat to allow to use `setColModelMetadata` for multiple grids or to use
````JavaScript
$.jgrid.extend({
	setColModelMetadata: function (savecolfunc, successfunc, errorfunc) {
		var $t = this[0];
		...
	}
});
````

In any way I recommend you to validate the code in JSLint or JSHint. For example you can add the lines
````JavaScript
/*jslint continue: true, nomen: true, plusplus: true, unparam: true, todo: true, vars: true, white: true */
/*global jQuery */
````
directly before the line `(function($){` and to use http://www.jslint.com/ to validate your code. In the way you can fix many problems in the code before you start to debug it.

Best regards
Oleg
P.S. Can you provide a demo Visual Studio Project where you use ASP.NET OData, jqGrid and the Plugin. I could provide you my suggestions to improve it.

**Comment by OlegKi** [comment]
Hi Mark,

could you update `grid.odata.js` and fix all clear bugs? I plan soon publish the first version (4.8) of free jqGrid. I would like to include the fixed version of the plugin where at least the errors reported by JSLint are fixed. You should remove definition of `var` inside of `for` because JavaScript language don't support loop-level variables. Even block level variables are not possible. The usage of `for (var i = 0, ...` construct makes the code wrong readable by users who don't knows details of JavaScript. You need define variables better out of the loop, for example on the top of the current function. The constructs `Unnecessary 'else' after disruption.` means that you can skip `else` after `if` in case of usage `return` in the `if` part. One can easy change the order of the functions included in the code. If you will have some technical problems you can contact me.

Moreover it would be very helpful for other users to include the link to test demo project which uses the plugin. It can increase the number of users which will use your plugin.

Best regards
Oleg

**Pull request merged**
