### PR TITLE
Added fixes to grid.odata.js

### PR DESCRIPTION
**Pull request by mirik123**
1) added global functions: **gridODataHelpers.resolveJsonReferences**, **gridODataHelpers.convertXmlToJson**
2) fixed bug that occured at executing **initWebApiTable** with **PreserveReferencesHandling.All**
3) added support of XML dataType for odata/metadata queries.
4) I hate GIT !!!!!

### CODE REVIEW

**Comment by OlegKi** [comment]
First about GitHub. I had many problem in the past too, but later I changed the style of working. Before I posted old pull requests I just prepared my changes *separately*. You can just save `grid.odata.js` in separate places. Before I posted new pull request I just **deleted** my old fork and created made the fork one more time. After that You could place modified version of `grid.odata.js` in plugin directory and post the pull request. It will be very quickly and will always work.

About your changes. The idea to support both XML and JSON is very good. Not all OData services support JSON metadata even in case of supporting JSON in the main data. On the other side you use `datatype` of data in request of metadata. I personally find it not so good. [jQuery.ajax](http://api.jquery.com/jquery.ajax/) have many possibilities in processing *dynamic* `dataType`. You can make for example request *without* specifying `dataType` parameter and later to detect the type of `data` in `success`/`done` handler.

About your changes. I don't understand why you need to make `gridODataHelpers` as global? Your current code looks like the following
````JavaScript
(function () {
    "use strict";
    window.gridODataHelpers = {
        resolveJsonReferences: function (json, refs) {
            ...
        },
        convertXmlToJson: function (xml) {
            ...
        }
    };
}());

(function ($) {
    "use strict";
    $.jgrid.extend({
        odataInit: function (options) {
            ...
        },
        odataGenColModel: function (options) {
            ...
        }
    });
}(jQuery));
````
Why you don't change it just as 
````JavaScript
(function ($) {
    "use strict";
    var gridODataHelpers = {
        resolveJsonReferences: function (json, refs) {
            ...
        },
        convertXmlToJson: function (xml) {
            ...
        }
    };

    $.jgrid.extend({
        odataInit: function (options) {
            ...
        },
        odataGenColModel: function (options) {
            ...
        }
    });
}(jQuery));
````
You will be able to use `gridODataHelpers` inside of both `odataInit` and `odataGenColModel`, but no **global** `gridODataHelpers` will be required. The changes will solve all problems reported by [JSLint](http://www.jslint.com/) too. In the same way you can move `resolveJsonReferences` and `convertXmlToJson` from `gridODataHelpers` object. I see no advantage of the usage of it in the current code. The only advantage could be is you would nee to set `this` to `gridODataHelpers` object, but you don't need it currently.

Best regards
Oleg
P.S. Do you have time to take a look in the demo project which I posted in [the comment](https://github.com/free-jqgrid/jqGrid/pull/18#issuecomment-81313943)? One can easy add editing to the demo. You can also add filling of initial data in [your demo](https://github.com/mirik123/jqGridSamples).

**Comment by mirik123** [comment]
I want to use resolveJsonReferences,convertXmlToJson directly in my sample ASP.NET project.
I believe if I make them local they become invisible from outside.

I saw your project. It uses simple List based data model. 
I don't want to oversimplify the code because it can have negative impact on resume :)

Regarding odata/metadata ajax dataType.
I'm familiar with WebApi odata services and they support both xml/json were json is preferred datatype.
I can also try to test it against WCF odata services from here: http://www.odata.org/odata-services.

**Comment by OlegKi** [comment]
There are a lot of *existing* global objects. One can just add property to the object instead of creating new one. For example `jQuery` is global object and one extend `jQuery.fn.` by registering of new jQuery plugin. jqGrid uses `$.jgrid`. So you can just register `$.jgrid.resolveJsonReferences` and `$.jgrid.convertXmlToJson` or `$.jgrid.oDataHelper.resolveJsonReferences` and `$.jgrid.oDataHelper.convertXmlToJson` or any other. It's better as to introduce new global objects. 

The main problem with your example: it display empty grid. It's better pre-load the data and allow to modify there.

The most OData examples which I found in Internet don't supported JSON in $metadata, but there still returns main data in JSON . What I mean is: how to integrate your plugin in the existing OData service? The first version of your code used XML for parsing, The last one uses **the same** format like `datatype`, but it seems to me one have no possibility to load JSON data from the service which provides $metadata only in XML format. Is't so?

**Comment by mirik123** [comment]
added fixes to grid.odata.js.
I'll also add to jqGridSamples repository client-side-only web site without EF part that should query against http://www.odata.org/odata-services.

**Comment by OlegKi** [comment]
Hi Mark,

I've merged the pull request, but I made [two small changes](https://github.com/free-jqgrid/jqGrid/commit/dfb33dc4689652a8b2b6ab83813ce81cc0ffd506):
 1. One should not use `$` as global variable. Instead of that `jQuery` is better. You can consider to merge two `(function ($) {...}(jQuery));` with only one.
 2. I renamed `$.jgrid.ODataHelper` to `$.jgrid.odataHelper` (please update your code too). One should use the first capital letter only if one defines **constructor**. If you look any other standard JavaScript libraries (see JavaScript tab [here](http://www.odata.org/libraries/), look at the fore from [here](http://olingo.apache.org/doc/javascript/download.html)) you will find only `odata` or `oData`. The name `$.jgrid.odataHelper` seems to me more corresponds to other methods (`odataInit` and `odataGenColModel`) which you use already.

I hope that you agree with the changes.

Best regards
Oleg

**Pull request merged**
