### PR TITLE
Use JQuery for expand/collapse

### PR DESCRIPTION
**Pull request by salimnanji**
Was finding that expand/collapse was incredibly slow on our project with grouping and frozen columns. Used Jquery functions to speed things up exponentially.

Also created a toggleAll method called using .jqGrid('toggleAll', true); or .jqGrid('toggleAll', false);

### CODE REVIEW

**Comment by OlegKi** [comment]
sorry, but you wrote about the performance of **the tree grid and frozen columns**, but you suggested some changes in **grouping module** (in `groupingToggle`). Where exactly you have performance problem? Do you analysed the problem which you have? What is the reason of the problem? Where is the code which you use? Can you provide the demo which demonstrates the problem? Which web browser you used during your performance tests? How you measure the performance? How many performance advantage get the suggested changes of the code?

I suggest that post first the issue where you describe the problem *before* posting the pull request, which suggestion to change the code. If you post the code, then you should be very careful. The code which you post use "tree level" terminology in comment, use separate `var` declaration for every variable (the existing code use another style because of hoisting of variables in JavaScript language), you use `var minusIcon = groupingConfig.minusicon.split(' ')[1];` which very suspected and seems be wrong. I can continue...

I suggest that **you first clear describe the original problem** with the demo which uses the current code of jqGrid. Another demo should use modified code and one can see the benefit of suggested changes. To measure the performance one can use `var startTime = new Date();` at the beginning of measured code fragment and then use `new Date() - startTime` at the end on measured code fragment. In the way one measure the performance and the suggested changes. Look for example [the post](http://www.trirand.com/blog/?page_id=393/bugs/improving-performance-of-loading-local-data-in-jqgrid) and [the answer](http://stackoverflow.com/a/25532422/315935), which contains [the first demo](http://www.ok-soft-gmbh.com/jqGrid/performane-90000.htm), which demonstrates original performance problem and [the demo1](http://www.ok-soft-gmbh.com/jqGrid/performane-90000_.htm) and [demo2](http://www.ok-soft-gmbh.com/jqGrid/performane-90000__.htm), which demonstrates the results of suggested fix.

Could you provide the demo, which demonstrates the original performance problem at the beginning?

**Comment by OlegKi** [comment]
I could reproduce the performance problem with the usage frozen columns in data grouping. I agree that the code of `groupingToggle` can be improved, but it will practically make no changing the total performance. My analyse shows that the most expensive is `$($t).triggerHandler("jqGridGroupingClickGroup", [hid, collapsed]);` line of `groupingToggle`. In other words, the code of `fixDiv` from `setFrozenColumns` is the bottleneck of the performance problem in the usage frozen columns in data grouping. I will look later how one can fix the problem.

**Comment by salimnanji** [comment]
I'll be able to make a test later tonight for you.

Found that when you group by 2 columns, and have 1000 rows+ (gets very
noticeable), in all browsers (with IE being slowest), it takes about 10
seconds to toggle a row. When toggling all columns, this can take up to
60sec+ depending on the number of columns.

The methods I created bring this down to a fraction of a second.

**Comment by salimnanji** [comment]
I think I may have mixed up the notation of free grid and groupings. I
meant performance for grouping, not tree grids. Just use frozen columns and
groupings on our grids.

**Comment by OlegKi** [comment]
The reason of good performance of your code is easy. It contains **no line**
```JavaScript
($t).triggerHandler("jqGridGroupingClickGroup", [hid, collapsed]);
```
which is the bottleneck in the original code.

What I wrote you before is the way how to report a problem. I can't just merge your changes without any testing. You wrote that you made some tests, but you don't posted the corresponding URLs. Moreover it seems to me that you still don't measure the results exactly. I wrote already in my first post how one can do this. Now I created small JSFiddle code which contains
```JavaScript
$.jgrid.extend({
    groupingToggle: function (hid) {
        this.each(function () {
          /* the copy of existing code of groupingToggle from GitHub
             with minimal modification. The line is inserted as the beginning*/
            var startTime = new Date();
           /* old code*/
            alert ((new Date() - startTime) + " ms for groupingToggle");
        });
        return false;
    }
});
$(function () {
    /* the code of the demo */
});
```
In the way one can **overwrite** the code of `groupingToggle` method inserted from `jquery.jqgrid.src.js`. I used almost the same code. I made minimal modifications to displaying the time in ms in alert (one could use console output alternative).

You can see the demo here: http://jsfiddle.net/OlegKi/e3ouywqs/. If you comment the line `.jqGrid("setFrozenColumns")` or the line with `$($t).triggerHandler("jqGridGroupingClickGroup", [hid, collapsed]);` all will work much more quickly.

Now I modified the demo by replacing the code of `groupingToggle` method with your code. I inserted of cause the lines
```JavaScript
var startTime = new Date();
var collapsed = false;
```
setting of `collapsed = true` inside of `if ($hIcon.hasClass(plusIcon)) {...}` block and adding the lines
```JavaScript
$($t).triggerHandler("jqGridGroupingClickGroup", [hid, collapsed]);
if ($.isFunction(p.onClickGroup)) {
    p.onClickGroup.call($t, hid, collapsed);
}
alert ((new Date() - startTime) + " ms for groupingToggle");
```
at the end of your version of `groupingToggle` method.
You can see the demo here: http://jsfiddle.net/OlegKi/e3ouywqs/1/.

Now you will see (end measure) **the real performance benefit** of your changes. Everybody can reproduce the reported problem, measure the ordinal performance by modification of the line `getGridData(100)` to `getGridData(1000)` for example (1000 rows instead of 100 rows), commenting some other lines or making more important changes. One can reproduce the problem, measure the performance and one can make the same tests with suggested modification. It would be good communication way, which bring the best productivity in my opinion.

I wrote you that the original code of `groupingToggle` method is not perfect. It's not written by me. I have no problem to change it, but the most important for me is localization of the bottleneck of the performance problem and fixing it. After that one can additionally improve the code of `groupingToggle` too.

I wrote you that I will continue to analyse the problem. I have some ideas how to improve the performance dramatically, but I have to do some other things now first and then I have to make some code changes to implement the ideas and to make the corresponding tests. I will post you later after I will have additional information. If you find out some additional information yerself, please send it me.

In any way thank you for reporting the problem with performance of frozen columns (in combination with data grouping). We will fix the problem.

**Comment by salimnanji** [comment]
Thank you. Will take your suggestions for future.

**Comment by OlegKi** [comment]
Hi Salim,

The demo http://jsfiddle.net/OlegKi/e3ouywqs/2/ includes my first attempt of modifications of `groupingToggle` and `setFrozenColumns`. It's still not final version, but you can see already dramatic improvement of the performance compared with the previous demos. I will make more changes in code of `setFrozenColumns`, which should give some additional benefits.

Although changes of `setFrozenColumns` makes the most performance improvement I will change the code of `groupingToggle` based on your suggestions. I think that the usage of `nextUntil` is a good idea.

I will continue tomorrow with the next changing of the code and the tests.

**Comment by salimnanji** [comment]
That looks wonderful so far! The frozen columns changes seems to have fixed
an outstanding bug I saw for when you had 1000+ rows and frozen columns in
IE and tried scrolling down (frozen panes and regular panes would scroll at
different speeds).

Salim Nanji
T: 416-407-4008

**Comment by OlegKi** [comment]
I posted to GitHub the changes, which I promised to implement. Please test the results and confirm that the main performance problem is solved now. The demo http://jsfiddle.net/OlegKi/e3ouywqs/4/ demonstrates the results of working new code. It uses subclassing to measure the time of working `groupingToggle` method:
```JavaScript
var orgGroupingToggle = $.fn.jqGrid.groupingToggle

$.jgrid.extend({
    groupingToggle: function () {
        var startTime = new Date(),
            restlt = orgGroupingToggle.apply(this, $.makeArray(arguments));
        
        alert ((new Date() - startTime) + " ms for groupingToggle");
        return restlt;
    }
});
```

I will try now to review the code of `groupingToggle` once more and include the usage of `jQuery.nextUntil`, which you initially suggested. I will include the method `toggleAll` too.

**One more question to you.** What do you think about introducing one more option of grouping which makes `toggleAll` on **double click** on "+" (expand) icon of grouping? By usage the option one could on/off the feature. The double click handle will just call new `toggleAll` method.

**Comment by salimnanji** [comment]
Works well in IE/Chrome with the newest version.
Double click toggleAll on icon grouping with an on/off feature sounds like a good idea!

**Comment by OlegKi** [comment]
I posted just now a lot of changes in `setFrozenColumns` and full rewrote `groupingToggle`. The performance is essentially improved now. You can test the results on http://jsfiddle.net/OlegKi/e3ouywqs/4/ and compare it with http://jsfiddle.net/OlegKi/e3ouywqs/7/ which uses jqGrid 4.9.2 code. If you changes `gridData = getGridData(100);` to `gridData = getGridData(1000);` in both demos you will see the differences in the performance the mostly clear.

By the way, the usage of `jQuery.nextUntil` is not possible because of two important cases: 1) the usage of group which have summary row `jqfoot` 2) collapsing of the last group of the second/third and so on level. It's next (until) class can be and class of some level which higher as the current. All the cases required setting of *multiple* until classes which is not possible in `jQuery.nextUntil`. Moreover the exact implementation of expanding is a little more complex as can be implemented in code which you posted. On the other side I looks through the code of `jQuery.nextUntil` and the new version of `groupingToggle` uses all advantages existing in `jQuery.nextUntil`. As the result I get additional performance advantage.

One more remark to you. I implemented new simple option `maxHeight` which can be practical for you. One can don't specify and `height` (the default value is `"auto"`), but to use `maxHeight: 300` for example. It displays small grids in case of small number of visible rows, but still reduce the maximal height till `300px` in case of usage large number or visible rows.

The last remark. I will implement `toggleAll` method and the option which expends all subgroups on double click on "+" (expand) icon of grouping. I will do it later, but I close already the current pull request because it can't be applied.

Thank you for interesting discussion, which helps to improve free jqGrid code.

**Pull request closed without merging**
